

--Drop Tables if they exist
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_NAME = N'USER_REGISTRY')
            BEGIN
            DROP TABLE USER_REGISTRY
            END

IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_NAME = N'CALANDER_LIST')
            BEGIN
            DROP TABLE CALANDER_LIST
            END

--Create tables
CREATE TABLE USER_REGISTRY (
USER_ID INTEGER PRIMARY KEY IDENTITY(1,1),--consider using userName as prime key
USER_NAME VARCHAR(15) UNIQUE NOT NULL, --some way to identify why an insert fail
USER_PASSWORD VARCHAR(30) NOT NULL, --hide this information
USER_PRIVLAGE INT NOT NULL DEFAULT 1,
USER_ONLINE  BIT NOT NULL DEFAULT 0,
USER_SESSION VARBINARY(MAX)
);
INSERT INTO dbo.USER_REGISTRY(USER_NAME,USER_PASSWORD,USER_PRIVLAGE,USER_ONLINE)
VALUES('testUser','123test','0','0');

CREATE TABLE CALANDER_LIST (
LIST_ID INTEGER PRIMARY KEY IDENTITY(1,1),
CLASS_ID INT NOT NULL,
ROOM_ID INT NOT NULL,
LIST_YEAR INT NOT NULL,
LIST_MONTH INT,
LIST_WEEK INT,
LIST_DAY INT,
START_TIME VARCHAR(5) NOT NULL,
END_TIME VARCHAR(5) NOT NULL
);